### PR TITLE
Support towards other devices

### PR DESCRIPTION
**Pull request by mash-97**
It uses `os.getcwd()` to get the current directory.

### CODE REVIEW

**Review by ahammadshawki8 — CHANGES_REQUESTED** [review]
I was aware of the error and the function. I just created that issue for increasing the number of issues on my GitHub as well as increase open-source collaboration on my projects.

However, as you used the os.getcwd() method. It will still don't work on Linux and Mac machine as their default path character is forward slash not bask-slash.

So, I prefer if you change the constant file variable and use os.path.joi() instead of current string concatenation. Also change the variables in backup_restore.py files. 🐍

**Comment by mash-97** [comment]
```
ADMIN_FILE 
DOCTOR_FILE 
PATIENT_FILE 
EMPLOYEE_FILE
```
These constants were defined two times, should we make it one time by defining as global?

**Comment by mash-97** [comment]
I've made changes what you asked for!

**Comment by ahammadshawki8** [comment]
Great,  after reviewing them I will merge. You don't need to make the
variables global.

**Review by ahammadshawki8 — APPROVED** [review]
Great work! Approved and merged to the main branch

**Pull request merged**
